import { TaskTemplate } from './types';

export const TASK_TEMPLATES: TaskTemplate[] = [
  {
    id: 'code-review',
    name: '代码审计',
    description: '对源代码进行安全审计，检测潜在漏洞和安全风险',
    category: 'security',
    icon: 'Shield',
    color: 'blue',
    parameters: [
      {
        name: 'targetPath',
        label: '目标路径',
        type: 'text',
        required: true,
        placeholder: '例如: /src/main/java',
        description: '要审计的代码目录或文件路径',
      },
      {
        name: 'language',
        label: '编程语言',
        type: 'select',
        required: true,
        options: ['Java', 'Python', 'PHP', 'JavaScript', 'Go', 'C/C++', 'Other'],
        defaultValue: 'Java',
      },
      {
        name: 'depth',
        label: '审计深度',
        type: 'select',
        required: false,
        options: ['快速扫描', '标准审计', '深度分析'],
        defaultValue: '标准审计',
        description: '快速扫描侧重常见漏洞，深度分析包含逻辑漏洞',
      },
      {
        name: 'focusAreas',
        label: '重点关注',
        type: 'textarea',
        required: false,
        placeholder: '例如: SQL注入、XSS、认证绕过...',
        description: '指定需要重点关注的漏洞类型',
      },
    ],
    tags: ['源代码', '静态分析', '漏洞检测'],
  },
  {
    id: 'vuln-scan',
    name: '漏洞扫描',
    description: '自动化扫描已知漏洞类型，快速识别安全隐患',
    category: 'security',
    icon: 'Bug',
    color: 'red',
    parameters: [
      {
        name: 'targetUrl',
        label: '目标地址',
        type: 'url',
        required: true,
        placeholder: 'https://example.com',
        description: '要扫描的Web应用URL地址',
      },
      {
        name: 'scanType',
        label: '扫描类型',
        type: 'select',
        required: true,
        options: ['被动扫描', '主动扫描', '全面扫描'],
        defaultValue: '主动扫描',
      },
      {
        name: 'vulnCategories',
        label: '漏洞类型',
        type: 'select',
        required: false,
        options: ['全部类型', '注入类', '认证类', '信息泄露', '配置错误'],
        defaultValue: '全部类型',
      },
      {
        name: 'outputFormat',
        label: '输出格式',
        type: 'select',
        required: false,
        options: ['详细报告', '摘要报告', 'JSON格式'],
        defaultValue: '详细报告',
      },
    ],
    tags: ['Web应用', '自动化', '快速扫描'],
  },
  {
    id: 'penetration-test',
    name: '渗透测试',
    description: '模拟攻击者视角进行Web应用渗透测试，发现深层漏洞',
    category: 'security',
    icon: 'Sword',
    color: 'orange',
    parameters: [
      {
        name: 'targetUrl',
        label: '目标地址',
        type: 'url',
        required: true,
        placeholder: 'https://example.com',
      },
      {
        name: 'testScope',
        label: '测试范围',
        type: 'textarea',
        required: true,
        placeholder: '例如: 登录模块、支付接口、用户管理...',
        description: '明确渗透测试的功能模块范围',
      },
      {
        name: 'authType',
        label: '认证方式',
        type: 'select',
        required: false,
        options: ['无需认证', '用户账号', '管理员账号', '双账号测试'],
        defaultValue: '用户账号',
      },
      {
        name: 'testStrategy',
        label: '测试策略',
        type: 'select',
        required: false,
        options: ['黑盒测试', '灰盒测试', '白盒测试'],
        defaultValue: '灰盒测试',
        description: '黑盒无源码，灰盒有部分信息，白盒有完整源码',
      },
      {
        name: 'authInfo',
        label: '认证信息',
        type: 'textarea',
        required: false,
        placeholder: '测试账号: test@example.com / password123',
        description: '提供测试用的账号密码或API密钥',
      },
    ],
    tags: ['Web应用', '人工测试', '深层漏洞'],
  },
  {
    id: 'threat-modeling',
    name: '威胁建模',
    description: '从架构层面分析系统威胁，识别潜在攻击路径',
    category: 'security',
    icon: 'Network',
    color: 'purple',
    parameters: [
      {
        name: 'systemDesc',
        label: '系统架构描述',
        type: 'textarea',
        required: true,
        placeholder: '描述系统架构、主要组件、数据流向...',
        description: '提供系统整体架构和关键组件信息',
      },
      {
        name: 'keyAssets',
        label: '关键资产',
        type: 'textarea',
        required: true,
        placeholder: '例如: 用户数据、支付信息、API密钥...',
        description: '需要重点保护的数据和资源',
      },
      {
        name: 'trustBoundary',
        label: '信任边界',
        type: 'textarea',
        required: false,
        placeholder: '例如: 内部网络与外部网络的边界...',
        description: '系统中不同信任级别的边界划分',
      },
      {
        name: 'framework',
        label: '分析框架',
        type: 'select',
        required: false,
        options: ['STRIDE', 'DREAD', 'PASTA', '自定义'],
        defaultValue: 'STRIDE',
        description: '威胁建模方法论',
      },
    ],
    tags: ['架构分析', '风险评估', '设计阶段'],
  },
];

export function getTemplateById(id: string): TaskTemplate | undefined {
  return TASK_TEMPLATES.find(t => t.id === id);
}

export function getTemplatesByCategory(category: string): TaskTemplate[] {
  return TASK_TEMPLATES.filter(t => t.category === category);
}