import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
      '4xl': '2560px',
    },
    extend: {
      colors: {
        primary: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        zinc: {
          950: '#09090B',
          900: '#18181B',
          800: '#27272A',
          700: '#3F3F46',
          600: '#52525B',
          500: '#71717A',
          400: '#A1A1AA',
          300: '#D4D4D8',
          200: '#E4E4E7',
          100: '#F4F4F5',
        },
        dark: {
          bg: '#1c1c1e',
          surface: '#2c2c2e',
          'surface-hover': '#3a3a3c',
          'surface-alt': '#1c1c1e',
          border: '#3a3a3c',
          text: '#e5e5e5',
          'text-secondary': '#a1a1a3',
          'text-muted': '#7c7c7e',
        },
      },
      spacing: {
        'sidebar-collapsed': '64px',
        'sidebar-expanded': '240px',
        'header': '56px',
        'panel-sm': '240px',
        'panel-md': '320px',
        'panel-lg': '400px',
      },
      maxWidth: {
        'prose': '768px',
        'prose-wide': '896px',
        'prose-narrow': '640px',
        'content-sm': '640px',
        'content-md': '768px',
        'content-lg': '1024px',
        'content-xl': '1280px',
        'content-2xl': '1440px',
        'content-4k': '1600px',
        'screen-2xl': '1536px',
      },
      minWidth: {
        'card': '280px',
        'sidebar': '64px',
        'panel': '240px',
      },
      height: {
        'header': '56px',
        'footer': '48px',
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: '#e5e5e5',
            '--tw-prose-body': '#e5e5e5',
            '--tw-prose-headings': '#f5f5f5',
            '--tw-prose-lead': '#a1a1a3',
            '--tw-prose-links': '#818cf8',
            '--tw-prose-bold': '#f5f5f5',
            '--tw-prose-counters': '#7c7c7e',
            '--tw-prose-bullets': '#7c7c7e',
            '--tw-prose-hr': '#3a3a3c',
            '--tw-prose-quotes': '#a1a1a3',
            '--tw-prose-quote-borders': '#6366f1',
            '--tw-prose-captions': '#a1a1a3',
            '--tw-prose-code': '#818cf8',
            '--tw-prose-pre-code': '#e5e5e5',
            '--tw-prose-pre-bg': '#1c1c1e',
            '--tw-prose-th-borders': '#3a3a3c',
            '--tw-prose-td-borders': '#3a3a3c',
            '--tw-prose-invert-body': '#e5e5e5',
            '--tw-prose-invert-headings': '#f5f5f5',
            '--tw-prose-invert-lead': '#a1a1a3',
            '--tw-prose-invert-links': '#818cf8',
            '--tw-prose-invert-bold': '#f5f5f5',
            '--tw-prose-invert-counters': '#7c7c7e',
            '--tw-prose-invert-bullets': '#7c7c7e',
            '--tw-prose-invert-hr': '#3a3a3c',
            '--tw-prose-invert-quotes': '#a1a1a3',
            '--tw-prose-invert-quote-borders': '#6366f1',
            '--tw-prose-invert-captions': '#a1a1a3',
            '--tw-prose-invert-code': '#818cf8',
            '--tw-prose-invert-pre-code': '#e5e5e5',
            '--tw-prose-invert-pre-bg': '#1c1c1e',
            '--tw-prose-invert-th-borders': '#3a3a3c',
            '--tw-prose-invert-td-borders': '#3a3a3c',
          },
        },
        sm: {
          css: {
            fontSize: '14px',
            lineHeight: '1.6',
          },
        },
        lg: {
          css: {
            fontSize: '18px',
            lineHeight: '1.75',
          },
        },
      },
      animation: {
        'marquee': 'marquee 20s linear infinite',
        'marquee-reverse': 'marquee-reverse 20s linear infinite',
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'marquee-reverse': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      transitionProperty: {
        'width': 'width',
        'height': 'height',
        'spacing': 'margin, padding',
        'layout': 'width, height, margin, padding',
      },
      boxShadow: {
        'glow': '0 0 20px rgba(99, 102, 241, 0.15)',
        'glow-strong': '0 0 30px rgba(99, 102, 241, 0.25)',
        'card': '0 1px 2px 0 rgba(0, 0, 0, 0.2), 0 1px 3px 0 rgba(0, 0, 0, 0.15)',
        'card-hover': '0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -1px rgba(0, 0, 0, 0.25)',
      },
      borderRadius: {
        'card': '12px',
        'panel': '16px',
      },
    },
  },
  plugins: [
    typography,
  ],
};

export default config;