apiVersion: v1
kind: Secret
metadata:
  name: chirmera-postgresql-secret
  namespace: secflow-ns
type: Opaque
stringData:
  POSTGRES_DB: sechps
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: change-me-postgres-password
