apiVersion: v1
kind: Secret
metadata:
  name: chirmera-worker-secret
  namespace: secflow-ns
type: Opaque
stringData:
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: change-me-minio-secret
  JWT_SECRET: change-me-jwt-secret
  OPENCODE_DISABLE_MODELS_FETCH: "true"
  IS_SANDBOX: "1"
