apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeswarm-scheduler
  namespace: secflow-ns
  labels:
    app: scheduler
    component: scheduler
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: codeswarm.secflow.ai.icsl.huawei.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scheduler
                port:
                  number: 8080
