apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: codeswarm-worker
  namespace: secflow-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: codeswarm-worker
  minReplicas: 1
  maxReplicas: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 3
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
