// 权限常量定义
export const PERMISSIONS = {
  // 会话权限
  SESSION_CREATE: 'session:create',
  SESSION_READ: 'session:read',
  SESSION_UPDATE: 'session:update',
  SESSION_DELETE: 'session:delete',
  SESSION_SHARE: 'session:share',
  SESSION_REVERT: 'session:revert',

  // 用户管理权限
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_ASSIGN_ROLE: 'user:assign_role',

  // 角色管理权限
  ROLE_CREATE: 'role:create',
  ROLE_READ: 'role:read',
  ROLE_UPDATE: 'role:update',
  ROLE_DELETE: 'role:delete',
  ROLE_ASSIGN_PERMISSION: 'role:assign_permission',

  // 权限管理权限
  PERMISSION_CREATE: 'permission:create',
  PERMISSION_READ: 'permission:read',
  PERMISSION_UPDATE: 'permission:update',
  PERMISSION_DELETE: 'permission:delete',

  // 配置管理权限
  CONFIG_READ: 'config:read',
  CONFIG_UPDATE: 'config:update',
  CONFIG_DELETE: 'config:delete',

  // 搜索权限
  SEARCH_FILE: 'search:file',
  SEARCH_SYMBOL: 'search:symbol',
  SEARCH_TEXT: 'search:text',

  // 文件操作权限
  FILE_READ: 'file:read',
  FILE_WRITE: 'file:write',

  // 审计日志权限
  AUDIT_READ: 'audit:read',

  // 工作流权限
  WORKFLOW_CREATE: 'workflow:create',
  WORKFLOW_READ: 'workflow:read',
  WORKFLOW_UPDATE: 'workflow:update',
  WORKFLOW_DELETE: 'workflow:delete',
  WORKFLOW_SHARE: 'workflow:share',
  WORKFLOW_EXECUTE: 'workflow:execute',
  WORKFLOW_EXPORT: 'workflow:export',
  WORKFLOW_IMPORT: 'workflow:import',

  // 插件权限
  PLUGIN_CREATE: 'plugin:create',
  PLUGIN_READ: 'plugin:read',
  PLUGIN_UPDATE: 'plugin:update',
  PLUGIN_DELETE: 'plugin:delete',
  PLUGIN_TOGGLE: 'plugin:toggle',
  PLUGIN_EXECUTE: 'plugin:execute',

  // Agent权限
  AGENT_CHAT: 'agent:chat',
  AGENT_EXECUTE: 'agent:execute',
  AGENT_READ: 'agent:read',

  // 自主进化权限
  AUTONOMOUS_EVOLUTION_READ: 'autonomous_evolution:read',
  AUTONOMOUS_EVOLUTION_CREATE: 'autonomous_evolution:create',
  AUTONOMOUS_EVOLUTION_UPDATE: 'autonomous_evolution:update',
  AUTONOMOUS_EVOLUTION_DELETE: 'autonomous_evolution:delete',
  AUTONOMOUS_EVOLUTION_EXTRACT: 'autonomous_evolution:extract',
  AUTONOMOUS_EVOLUTION_INJECT: 'autonomous_evolution:inject',

  // 代码分析权限
  CODE_ANALYZE: 'code:analyze',
  CODE_READ: 'code:read',

  // 模型管理权限
  MODEL_CREATE: 'model:create',
  MODEL_READ: 'model:read',
  MODEL_UPDATE: 'model:update',
  MODEL_DELETE: 'model:delete',
  MODEL_TEST: 'model:test',

  // 通知管理权限
  NOTIFICATION_CREATE: 'notification:create',
  NOTIFICATION_READ: 'notification:read',
  NOTIFICATION_UPDATE: 'notification:update',
  NOTIFICATION_DELETE: 'notification:delete',

  // 技能权限
  SKILL_CREATE: 'skill:create',
  SKILL_READ: 'skill:read',
  SKILL_UPDATE: 'skill:update',
  SKILL_DELETE: 'skill:delete',
  SKILL_EXECUTE: 'skill:execute',

  // Skills Governance 权限
  SKILL_GOVERNANCE_READ: 'skill-governance:read',
  SKILL_GOVERNANCE_UPDATE: 'skill-governance:update',
  SKILL_MERGE: 'skill:merge',
  SKILL_APPROVE: 'skill:approve',

  // 漏洞权限
  VULNERABILITY_CREATE: 'vulnerability:create',
  VULNERABILITY_READ: 'vulnerability:read',
  VULNERABILITY_UPDATE: 'vulnerability:update',
  VULNERABILITY_DELETE: 'vulnerability:delete',

  // 评估权限
  EVALUATION_CREATE: 'evaluation:create',
  EVALUATION_READ: 'evaluation:read',
  EVALUATION_UPDATE: 'evaluation:update',
  EVALUATION_DELETE: 'evaluation:delete',

  // 项目权限
  PROJECT_CREATE: 'project:create',
  PROJECT_READ: 'project:read',
  PROJECT_UPDATE: 'project:update',
  PROJECT_DELETE: 'project:delete',

  // Token 统计权限
  TOKEN_READ: 'token:read',
  TOKEN_DETAIL: 'token:detail',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// 角色常量
export const ROLES = {
  ADMIN: 'admin',
  USER: 'user',
  VIEWER: 'viewer',
  DEVELOPER: 'developer',
  MANAGER: 'manager',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

// 默认角色权限映射
export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS), // 管理员拥有所有权限

  [ROLES.MANAGER]: [
    PERMISSIONS.SESSION_CREATE,
    PERMISSIONS.SESSION_READ,
    PERMISSIONS.SESSION_UPDATE,
    PERMISSIONS.SESSION_DELETE,
    PERMISSIONS.SESSION_SHARE,
    PERMISSIONS.SESSION_REVERT,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.CONFIG_READ,
    PERMISSIONS.CONFIG_UPDATE,
    PERMISSIONS.SEARCH_FILE,
    PERMISSIONS.SEARCH_SYMBOL,
    PERMISSIONS.SEARCH_TEXT,
    PERMISSIONS.FILE_READ,
    PERMISSIONS.FILE_WRITE,
    PERMISSIONS.AUDIT_READ,
    // 工作流权限
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_UPDATE,
    PERMISSIONS.WORKFLOW_DELETE,
    PERMISSIONS.WORKFLOW_SHARE,
    PERMISSIONS.WORKFLOW_EXECUTE,
    PERMISSIONS.WORKFLOW_EXPORT,
    PERMISSIONS.WORKFLOW_IMPORT,
    // 插件权限
    PERMISSIONS.PLUGIN_CREATE,
    PERMISSIONS.PLUGIN_READ,
    PERMISSIONS.PLUGIN_UPDATE,
    PERMISSIONS.PLUGIN_DELETE,
    PERMISSIONS.PLUGIN_TOGGLE,
    PERMISSIONS.PLUGIN_EXECUTE,
    // Agent权限
    PERMISSIONS.AGENT_CHAT,
    PERMISSIONS.AGENT_EXECUTE,
    PERMISSIONS.AGENT_READ,
    // 自主进化权限
    PERMISSIONS.AUTONOMOUS_EVOLUTION_READ,
    PERMISSIONS.AUTONOMOUS_EVOLUTION_CREATE,
    PERMISSIONS.AUTONOMOUS_EVOLUTION_UPDATE,
    PERMISSIONS.AUTONOMOUS_EVOLUTION_DELETE,
    PERMISSIONS.AUTONOMOUS_EVOLUTION_EXTRACT,
    PERMISSIONS.AUTONOMOUS_EVOLUTION_INJECT,
    // 代码分析权限
    PERMISSIONS.CODE_ANALYZE,
    PERMISSIONS.CODE_READ,
    // 模型管理权限
    PERMISSIONS.MODEL_CREATE,
    PERMISSIONS.MODEL_READ,
    PERMISSIONS.MODEL_UPDATE,
    PERMISSIONS.MODEL_DELETE,
    PERMISSIONS.MODEL_TEST,
    // 通知管理权限
    PERMISSIONS.NOTIFICATION_CREATE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.NOTIFICATION_DELETE,
    // 技能权限
    PERMISSIONS.SKILL_CREATE,
    PERMISSIONS.SKILL_READ,
    PERMISSIONS.SKILL_UPDATE,
    PERMISSIONS.SKILL_DELETE,
    PERMISSIONS.SKILL_EXECUTE,
    // 漏洞权限
    PERMISSIONS.VULNERABILITY_CREATE,
    PERMISSIONS.VULNERABILITY_READ,
    PERMISSIONS.VULNERABILITY_UPDATE,
    PERMISSIONS.VULNERABILITY_DELETE,
    // 评估权限
    PERMISSIONS.EVALUATION_CREATE,
    PERMISSIONS.EVALUATION_READ,
    PERMISSIONS.EVALUATION_UPDATE,
    PERMISSIONS.EVALUATION_DELETE,
    // 项目权限
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    // Token 权限
    PERMISSIONS.TOKEN_READ,
    PERMISSIONS.TOKEN_DETAIL,
  ],

  [ROLES.DEVELOPER]: [
    PERMISSIONS.SESSION_CREATE,
    PERMISSIONS.SESSION_READ,
    PERMISSIONS.SESSION_UPDATE,
    PERMISSIONS.SESSION_SHARE,
    PERMISSIONS.SEARCH_FILE,
    PERMISSIONS.SEARCH_SYMBOL,
    PERMISSIONS.SEARCH_TEXT,
    PERMISSIONS.FILE_READ,
    PERMISSIONS.CONFIG_READ,
    // 工作流权限
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_UPDATE,
    PERMISSIONS.WORKFLOW_EXECUTE,
    PERMISSIONS.WORKFLOW_EXPORT,
    PERMISSIONS.WORKFLOW_IMPORT,
    // Agent权限
    PERMISSIONS.AGENT_CHAT,
    PERMISSIONS.AGENT_EXECUTE,
    // 代码分析权限
    PERMISSIONS.CODE_ANALYZE,
    PERMISSIONS.CODE_READ,
    // 模型读取权限
    PERMISSIONS.MODEL_READ,
    // 技能权限
    PERMISSIONS.SKILL_CREATE,
    PERMISSIONS.SKILL_READ,
    PERMISSIONS.SKILL_UPDATE,
    PERMISSIONS.SKILL_EXECUTE,
    // 漏洞读取权限
    PERMISSIONS.VULNERABILITY_READ,
    // 评估权限
    PERMISSIONS.EVALUATION_CREATE,
    PERMISSIONS.EVALUATION_READ,
    // 项目权限
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
  ],

  [ROLES.USER]: [
    PERMISSIONS.SESSION_CREATE,
    PERMISSIONS.SESSION_READ,
    PERMISSIONS.SESSION_UPDATE,
    PERMISSIONS.SEARCH_FILE,
    PERMISSIONS.SEARCH_SYMBOL,
    PERMISSIONS.SEARCH_TEXT,
    PERMISSIONS.FILE_READ,
    PERMISSIONS.CONFIG_READ,
    // 工作流权限
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_EXECUTE,
    // Agent权限
    PERMISSIONS.AGENT_CHAT,
    PERMISSIONS.AGENT_EXECUTE,
    // 技能权限
    PERMISSIONS.SKILL_READ,
    PERMISSIONS.SKILL_EXECUTE,
    // 项目权限（普通用户可以创建和更新自己的项目）
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    // 评估权限（普通用户可以创建评估）
    PERMISSIONS.EVALUATION_CREATE,
    PERMISSIONS.EVALUATION_READ,
    // 模型权限（普通用户可以管理自己的模型）
    PERMISSIONS.MODEL_CREATE,
    PERMISSIONS.MODEL_READ,
    PERMISSIONS.MODEL_UPDATE,
    PERMISSIONS.MODEL_DELETE,
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.SESSION_READ,
    PERMISSIONS.SEARCH_FILE,
    PERMISSIONS.SEARCH_SYMBOL,
    PERMISSIONS.SEARCH_TEXT,
    PERMISSIONS.FILE_READ,
    PERMISSIONS.CONFIG_READ,
    // 工作流权限
    PERMISSIONS.WORKFLOW_READ,
    // 技能读取权限
    PERMISSIONS.SKILL_READ,
    // 项目读取权限
    PERMISSIONS.PROJECT_READ,
  ],
};
